version: '3.8'

services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: unless-stopped
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - nexus-data:/nexus-data
    environment:
      # Disables random admin password, password will be: 'admin123', username: 'admin', if not disabled password will be in 'nexus-data/admin.password'
      - NEXUS_SECURITY_RANDOMPASSWORD=false

volumes:
  nexus-data:
    driver: local